<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Grant Sinclair" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="../img/favicon.ico">
    <title>Project 2 Modeling Data Analysis</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../blog/">BLOG</a></li>
        
        <li><a href="../projects/">PROJECTS</a></li>
        
        <li><a href="../resume.pdf">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../project2/">Project 2 Modeling Data Analysis</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          May 13, 2020
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<pre class="r"><code>#DATASET 
library(tidyverse)
library(&quot;readxl&quot;)
cars &lt;- read.csv(&quot;~/cars.csv&quot;)
sdata &lt;- read.csv(&quot;~/sdatareal.csv&quot;)

library(ggplot2)
head(cars)</code></pre>
<pre><code>##   X speed dist
## 1 1     4    2
## 2 2     4   10
## 3 3     7    4
## 4 4     7   22
## 5 5     8   16
## 6 6     9   10</code></pre>
<pre class="r"><code>glimpse(cars)</code></pre>
<pre><code>## Observations: 50
## Variables: 3
## $ X &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
15, 16, 17, 18, 19, 20, 21, 22, 23, …
## $ speed &lt;int&gt; 4, 4, 7, 7, 8, 9, 10, 10, 10, 11, 11, 12,
12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 1…
## $ dist &lt;int&gt; 2, 10, 4, 22, 16, 10, 18, 26, 34, 17, 28,
14, 20, 24, 28, 26, 34, 34, 46, 26, 36, 6…</code></pre>
<pre class="r"><code>cars &lt;- as.data.frame(cars) 
head(sdata)</code></pre>
<pre><code>##   X speed period warning pair ticket
## 1 1    26      1       1    1    yes
## 2 2    26      1       1    1    yes
## 3 3    26      1       1    1    yes
## 4 4    26      1       1    1    yes
## 5 5    27      1       1    1    yes
## 6 6    28      1       1    1    yes</code></pre>
<pre class="r"><code>sdata &lt;- as.data.frame(sdata) 
glimpse(sdata)</code></pre>
<pre><code>## Observations: 8,437
## Variables: 6
## $ X &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
15, 16, 17, 18, 19, 20, 21, 22, 23…
## $ speed &lt;int&gt; 26, 26, 26, 26, 27, 28, 28, 28, 28, 29,
29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 3…
## $ period &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
## $ warning &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
## $ pair &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
## $ ticket &lt;fct&gt; yes, yes, yes, yes, yes, yes, yes, yes,
yes, yes, yes, yes, yes, yes, yes, yes, y…</code></pre>
<pre class="r"><code>#Joining
carspeedfulljoin&lt;-inner_join(cars, sdata, by= c(&quot;speed&quot;, &quot;speed&quot;), suffix=c(&quot;cars&quot;, &quot;sdata&quot;))
glimpse(carspeedfulljoin)</code></pre>
<pre><code>## Observations: 258
## Variables: 8
## $ Xcars &lt;int&gt; 36, 37, 38, 39, 39, 39, 39, 40, 40, 40,
40, 41, 41, 41, 41, 42, 42, 42, 42, 43, 4…
## $ speed &lt;int&gt; 19, 19, 19, 20, 20, 20, 20, 20, 20, 20,
20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 2…
## $ dist &lt;int&gt; 36, 46, 68, 32, 32, 32, 32, 48, 48, 48, 48,
52, 52, 52, 52, 56, 56, 56, 56, 64, 6…
## $ Xsdata &lt;int&gt; 2101, 2101, 2101, 2102, 3301, 3401, 6824,
2102, 3301, 3401, 6824, 2102, 3301, 340…
## $ period &lt;int&gt; 2, 2, 2, 2, 2, 1, 3, 2, 2, 1, 3, 2, 2, 1,
3, 2, 2, 1, 3, 2, 2, 1, 3, 1, 1, 1, 2, …
## $ warning &lt;int&gt; 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1,
2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, …
## $ pair &lt;int&gt; 7, 7, 7, 7, 10, 10, 7, 7, 10, 10, 7, 7, 10,
10, 7, 7, 10, 10, 7, 7, 10, 10, 7, 2,…
## $ ticket &lt;fct&gt; yes, yes, yes, yes, yes, yes, yes, yes,
yes, yes, yes, yes, yes, yes, yes, yes, y…</code></pre>
<p><em>Introduction:</em> <em>The dataset I chose for this project is the same dataset I used for project 1. I will be using the joined version of the two datasets for this project. The two data sets were chosen from <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a> and are having to due with cars that had been pulled over and whether or not they received a ticket. While this data may seem mundane, I chose it because I believe I may find a strong correlation between an unthought of variable and whether or not a car receieves a ticket. The data I am analyzing contains the main variables speed(how fast the vehicle was going when pulled over), distance(how far the car travel before stopping), period(the time of day the car was pulled over, distinguished by 3, 8 hour periods), warning(whether or not the vechicle received a warning, pair(how many people were in the given vehicle), and ticket (whether or not the vehicle recieved a ticket). Initially, the strongest association I may expect to see is between time period and people in the car, as certain times of day may increase the amount of people traveling together. For example more people may travel together at night due to dinner plans or an evening event. Intutively, the other variables would not seem to have a strong assocation, however I am interested to see if there is an unexpected assocation. The data has 8 variables and 258 observations.</em></p>
<pre class="r"><code>project2dat &lt;- manova(cbind(speed,period,pair)~ticket,data=carspeedfulljoin)
summary(project2dat)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## ticket 1 0.32789 41.306 3 254 &lt; 2.2e-16 ***
## Residuals 256
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(project2dat)</code></pre>
<pre><code>## Response speed :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## ticket 1 4.01 4.0059 2.1068 0.1479
## Residuals 256 486.77 1.9014
##
## Response period :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## ticket 1 27.204 27.2038 52.73 4.591e-12 ***
## Residuals 256 132.071 0.5159
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response pair :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## ticket 1 315.95 315.949 44.475 1.578e-10 ***
## Residuals 256 1818.60 7.104
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>pairwise.t.test(carspeedfulljoin$speed,carspeedfulljoin$ticket,p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: carspeedfulljoin$speed and carspeedfulljoin$ticket
##
## no
## yes 0.15
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(carspeedfulljoin$period,carspeedfulljoin$ticket,p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: carspeedfulljoin$period and
carspeedfulljoin$ticket
##
## no
## yes 4.6e-12
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(carspeedfulljoin$pair,carspeedfulljoin$ticket,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  carspeedfulljoin$pair and carspeedfulljoin$ticket 
## 
##     no     
## yes 1.6e-10
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#error
1-(.95)^16</code></pre>
<pre><code>## [1] 0.5598733</code></pre>
<pre class="r"><code>.05/16</code></pre>
<pre><code>## [1] 0.003125</code></pre>
<p><em>Running a manova to test to see if speed,time period, and group size had a mean difference against ticket status, it seems that there was as the p-value generated was less than 0.05 and was 2.2e-16. After running an manova, an anova was used to test to see which ones of the variables had a mean difference. Time period and group pair were the only variables that had a mean difference while speed did not as the p-value was 0.1479 and the other p-values were below 0.05. After the anova, a pairwise t test was run for speed,period , and pair. Although speed did not show to have a mean difference in the anova test, it was run anyways for fun :). The pairwise t-tests showed that the period and pair variables showed a difference between yes and no ticket status, as they were below 0.05. Speed on the other hand, did not show a difference between yes and no ticket status.</em></p>
<pre class="r"><code>#Randomized Testing
carspeedfulljoin%&gt;%group_by(ticket)%&gt;%summarize(mean_speed=mean(speed))</code></pre>
<pre><code>## # A tibble: 2 x 2
##   ticket mean_speed
##   &lt;fct&gt;       &lt;dbl&gt;
## 1 no           24.0
## 2 yes          23.6</code></pre>
<pre class="r"><code>24-23.6</code></pre>
<pre><code>## [1] 0.4</code></pre>
<pre class="r"><code>rand_dist&lt;-vector()
for(i in 1:5000){
Randata&lt;-data.frame(ticket=sample(carspeedfulljoin$ticket),speed=carspeedfulljoin$speed)
rand_dist[i]&lt;-mean(Randata[Randata$ticket==&quot;yes&quot;,]$speed)-
mean(Randata[Randata$ticket==&quot;no&quot;,]$speed)}
mean(rand_dist&gt;0.4)*2</code></pre>
<pre><code>## [1] 0.2752</code></pre>
<pre class="r"><code>{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;);abline(v=0.4,col=&quot;red&quot;)}</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /> <em>A randomized test was used to take a sample of ticket status and pullit 5,000 times and then take the mean of yes and no ticket status of speed were subtracted to find the difference. After running a randomized test, I then found the p-value of a two-tailed test and it was greater than 0.05, as it was 0.2364. I then plotted a histogram to show the null distribution and test statistic. The null hypothesis is that there is no difference in speed in yes and no ticket status, and the alternative hypothesis is that there is a difference in speed in yes and no ticket status. From the randomized test and finding the p-value, we fail to reject the null hypothesis.</em></p>
<pre class="r"><code>#Linear Regression

fitdat &lt;- lm(period~speed*ticket, data=carspeedfulljoin)
coef(fitdat)</code></pre>
<pre><code>## (Intercept) speed ticketyes speed:ticketyes
## 3.000000e+00 -3.107139e-16 -6.139303e-01 -2.545601e-02</code></pre>
<pre class="r"><code>ggplot(fitdat, aes(x=speed,y=period, color=ticket)) +geom_point(shape=1) + geom_smooth(method = &quot;lm&quot;) + ggtitle (&quot;Linear Regression Predicting Period with Speed and Ticket Status&quot;) + ylab(&quot;Time Period&quot;) + xlab(&quot;Speed&quot;)+ labs(color=&quot;Ticket Status&quot;)</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#assumptions
resids&lt;-fitdat$residuals
fitvals&lt;-fitdat$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids), bins=20)</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-4-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_qq(aes(sample=resids))+geom_qq_line()</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-4-4.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#robust standard errors
summary(fitdat)$coef[,1:2] #uncorrected</code></pre>
<pre><code>##                      Estimate Std. Error
## (Intercept)      3.000000e+00  6.5724738
## speed           -3.107139e-16  0.2732017
## ticketyes       -6.139303e-01  6.6182261
## speed:ticketyes -2.545601e-02  0.2751732</code></pre>
<pre class="r"><code>#corrected code here
coeftest(fitdat, vcov = vcovHC(fitdat))[,1:2] </code></pre>
<pre><code>##                      Estimate   Std. Error
## (Intercept)      3.000000e+00 3.203062e-13
## speed           -3.107139e-16 1.000957e-14
## ticketyes       -6.139303e-01 7.581984e-01
## speed:ticketyes -2.545601e-02 3.220238e-02</code></pre>
<p><em>After running a linear regression,the coefficent estimates for speed was -3.107139e-16, yes for ticket status was -6.139303e-01 and the speed:yes for ticket status was -2.545601e-02. I then plotted Speed vs Time Period in yes and no ticket status and saw that there was a higher interaction in yes than no ticket status. I then checked assumptions, and every single one was failed. The assumption graphs did not exhibit, homoskedacity, normality, or linearity, and were very weird. Thus, I am taking the results with a grain of salt.</em></p>
<pre class="r"><code>#Bootstrapped Standard Error
library(ggplot2)
boot&lt;-carspeedfulljoin[sample(nrow(carspeedfulljoin),replace=TRUE),]
samp_distn&lt;-replicate(5000, {
boot&lt;-carspeedfulljoin[sample(nrow(carspeedfulljoin),replace=TRUE),]
fitdat2&lt;-lm(pair~speed*ticket,data=carspeedfulljoin)
coef(fitdat2)
})
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) speed ticketyes speed:ticketyes
## 1           0     0         0               0</code></pre>
<pre class="r"><code>#Logistic Regression 
install.packages(&#39;cluster&#39;)
library(cluster)
library(tidyverse)
fitdat2&lt;-glm(ticket~period+speed+pair, data=carspeedfulljoin, family=&quot;binomial&quot;)
coeftest(fitdat2)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                Estimate  Std. Error z value Pr(&gt;|z|)
## (Intercept)  3.3569e+02  1.4561e+05  0.0023   0.9982
## period      -7.0423e+01  2.0292e+04 -0.0035   0.9972
## speed        2.6762e-02  5.1175e+03  0.0000   1.0000
## pair        -1.4652e+01  4.7412e+03 -0.0031   0.9975</code></pre>
<pre class="r"><code>#confusion matrix
prob &lt;- predict(fitdat2,type=&quot;response&quot;)
table(predict=as.numeric(prob&gt;.5),yes=carspeedfulljoin$warning)%&gt;%addmargins</code></pre>
<pre><code>##        yes
## predict   1   2 Sum
##     0     9  11  20
##     1   187  51 238
##     Sum 196  62 258</code></pre>
<pre class="r"><code>class_diag&lt;-function(prob,yes){
tab&lt;-table(factor(prob&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),yes)
acc=sum(diag(tab))/sum(tab)
sens=tab[2,2]/colSums(tab)[2]
spec=tab[1,1]/colSums(tab)[1]
ppv=tab[2,2]/rowSums(tab)[2]
if(is.numeric(yes)==FALSE &amp; is.logical(yes)==FALSE) yes&lt;-as.numeric(yes)-1
#CALCULATE EXACT AUC
ord&lt;-order(prob, decreasing=TRUE)
prob &lt;- prob[ord]; yes &lt;- yes[ord]
TPR=cumsum(yes)/max(1,sum(yes))
FPR=cumsum(!yes)/max(1,sum(!yes))
dup&lt;-c(prob[-1]&gt;=prob[-length(prob)], FALSE)
TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
n &lt;- length(TPR)
auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
data.frame(acc,sens,spec,ppv,auc)
}

class_diag(prob,carspeedfulljoin$ticket)</code></pre>
<pre><code>##     acc sens spec ppv auc
## yes   1    1    1   1   1</code></pre>
<pre class="r"><code>#ROCplot
library(plotROC)

carspeedfulljoin$logit &lt;- predict(fitdat, data=carspeedfulljoin, type=&quot;response&quot;)
carspeedfulljoin$ticket &lt;-factor(carspeedfulljoin$ticket, levels=c(&quot;yes&quot;,&quot;no&quot;))
carspeedfulljoinlog &lt;- carspeedfulljoin%&gt;% mutate(ticket=ifelse(ticket==&quot;yes&quot;,&quot;yes&quot;,&quot;no&quot;))
ggplot(carspeedfulljoinlog, aes(logit,fill=ticket))+geom_density(alpha=.3)+geom_vline(xintercept = 0,lty=2)+ggtitle(&quot;Density of log-odds by Ticket Status&quot;)</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>RocPlot &lt;- ggplot(carspeedfulljoin)+geom_roc(aes(d=ticket,m=prob),n.cut=0)
RocPlot</code></pre>
<p><img src="../project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(RocPlot)</code></pre>
<pre><code>##   PANEL group AUC
## 1     1    -1   1</code></pre>
<pre class="r"><code>#10-fold
set.seed(1234)
k=10
prodata&lt;-carspeedfulljoin[sample(nrow(carspeedfulljoin)),] #randomly order rows
folds&lt;-cut(seq(1:nrow(carspeedfulljoin)),breaks=k,labels=FALSE) #create folds
diags&lt;-NULL
for(i in 1:k){
## Create training and test sets
train&lt;-prodata[folds!=i,]
test&lt;-prodata[folds==i,]
yes&lt;-test$ticket
## Train model on training set
fitdat3&lt;-glm(ticket~.,data=carspeedfulljoin,family=&quot;binomial&quot;)
probs2&lt;-predict(fitdat3,newdata = test,type=&quot;response&quot;)
## Test model on test set (save all k results)
diags&lt;-rbind(diags,class_diag(probs2,yes))
}
apply(diags,2,mean)</code></pre>
<pre><code>##  acc sens spec  ppv  auc 
##  1.0  NaN  1.0  NaN  0.8</code></pre>
<p><em>A logistic regression was run and this time the intercepts tell us the interactions of speed, time period, and group size in a vehicle that receieved a ticket. The intercepts for period was -7.0423, speed was 2.6762e-02, and pair was -1.4652. The accuracy (1), sensitivity (1), specificity (1), and auc (1) was also computed. The auc is good since it is 1(the highest value) However, every value computed was 1 and is thus a little suspect. After running the 10-fold, the auc acutally decreased in value to 0.8.</em></p>
<pre class="r"><code>#LASSO
library(glmnet)
x &lt;- model.matrix(fitdat)[,-1]
y&lt;-as.matrix(carspeedfulljoin$ticket)
cv&lt;-cv.glmnet(x,y,family=&#39;binomial&#39;)
lassodat&lt;-glmnet(x,y,family=&#39;binomial&#39;,lambda=cv$lambda.1se)
coef(lassodat)</code></pre>
<pre><code>## 4 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                 s0
## (Intercept)      .
## speed            0
## ticketyes        .
## speed:ticketyes  .</code></pre>
<pre class="r"><code>set.seed(1234)
k=10
prodata2&lt;-carspeedfulljoin[sample(nrow(carspeedfulljoin)),]
folds&lt;-cut(seq(1:nrow(carspeedfulljoin)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){ # FOR EACH OF 10 FOLDS
train2&lt;-prodata2[folds!=i,] #CREATE TRAINING SET
test2&lt;-prodata2[folds==i,] #CREATE TESTING SET
yes2&lt;-test2$ticket

probs3&lt;- predict(fitdat,newdata=test2, type=&quot;response&quot;)
diags&lt;-rbind(diags,class_diag(probs3,yes2))
}
apply(diags,2,mean)</code></pre>
<pre><code>##        acc       sens       spec        ppv        auc 
## 0.07707692        NaN 0.00000000 0.07707692 0.80000000</code></pre>
<p>A lasso regression was done and the auc was actually lower than then when I ran the original logistic regression. The auc here is 0.8 and the one above was 1. This was after running the 10-fold as well, and the LASSO accuracy(0.07707692) was not as high when running the logistic regression. Overall my data was very weird which likely explains why the numbers generated were strange / not expected.</p>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../js/docs.min.js"></script>
<script src="../js/main.js"></script>

<script src="../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
